// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/squat/terraform-provider-lambda/internal/sdk/models/shared"
	"net/http"
)

type GetInstanceRequest struct {
	// The unique identifier (ID) of the instance
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetInstanceRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetInstanceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Instance *shared.ResponseInstance
	// Unauthorized.
	ErrorResponseBody *shared.ErrorResponseBody
}

func (o *GetInstanceResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetInstanceResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetInstanceResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetInstanceResponse) GetInstance() *shared.ResponseInstance {
	if o == nil {
		return nil
	}
	return o.Instance
}

func (o *GetInstanceResponse) GetErrorResponseBody() *shared.ErrorResponseBody {
	if o == nil {
		return nil
	}
	return o.ErrorResponseBody
}
