// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Error struct {
	// Unique identifier for the type of error
	Code ErrorCode `json:"code"`
	// Detailed description of the error
	Message string `json:"message"`
	// Suggestion of possible ways to fix the error.
	Suggestion *string `json:"suggestion,omitempty"`
}

func (o *Error) GetCode() ErrorCode {
	if o == nil {
		return ErrorCode("")
	}
	return o.Code
}

func (o *Error) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *Error) GetSuggestion() *string {
	if o == nil {
		return nil
	}
	return o.Suggestion
}
