// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type FileSystems struct {
	Data []FileSystem `json:"data"`
}

func (o *FileSystems) GetData() []FileSystem {
	if o == nil {
		return []FileSystem{}
	}
	return o.Data
}
