// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Specs struct {
	// Number of virtual CPUs
	Vcpus int64 `json:"vcpus"`
	// Amount of RAM, in gibibytes (GiB)
	MemoryGib int64 `json:"memory_gib"`
	// Amount of storage, in gibibytes (GiB).
	StorageGib int64 `json:"storage_gib"`
	// Number of GPUs
	Gpus int64 `json:"gpus"`
}

func (o *Specs) GetVcpus() int64 {
	if o == nil {
		return 0
	}
	return o.Vcpus
}

func (o *Specs) GetMemoryGib() int64 {
	if o == nil {
		return 0
	}
	return o.MemoryGib
}

func (o *Specs) GetStorageGib() int64 {
	if o == nil {
		return 0
	}
	return o.StorageGib
}

func (o *Specs) GetGpus() int64 {
	if o == nil {
		return 0
	}
	return o.Gpus
}

// InstanceType - Hardware configuration and pricing of an instance type
type InstanceType struct {
	// Name of an instance type
	Name string `json:"name"`
	// Long name of the instance type
	Description string `json:"description"`
	// Description of the GPU(s) in the instance type
	GpuDescription string `json:"gpu_description"`
	// Price of the instance type, in US cents per hour
	PriceCentsPerHour int64 `json:"price_cents_per_hour"`
	Specs             Specs `json:"specs"`
}

func (o *InstanceType) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *InstanceType) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *InstanceType) GetGpuDescription() string {
	if o == nil {
		return ""
	}
	return o.GpuDescription
}

func (o *InstanceType) GetPriceCentsPerHour() int64 {
	if o == nil {
		return 0
	}
	return o.PriceCentsPerHour
}

func (o *InstanceType) GetSpecs() Specs {
	if o == nil {
		return Specs{}
	}
	return o.Specs
}
