// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Data struct {
	// Hardware configuration and pricing of an instance type
	InstanceType InstanceType `json:"instance_type"`
	// List of regions, if any, that have this instance type available
	RegionsWithCapacityAvailable []Region `json:"regions_with_capacity_available"`
}

func (o *Data) GetInstanceType() InstanceType {
	if o == nil {
		return InstanceType{}
	}
	return o.InstanceType
}

func (o *Data) GetRegionsWithCapacityAvailable() []Region {
	if o == nil {
		return []Region{}
	}
	return o.RegionsWithCapacityAvailable
}

// InstanceTypes - OK
type InstanceTypes struct {
	// Dict of instance_type_name to instance_type and region availability.
	Data map[string]Data `json:"data"`
}

func (o *InstanceTypes) GetData() map[string]Data {
	if o == nil {
		return map[string]Data{}
	}
	return o.Data
}
