// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Region struct {
	// Short name of a region
	Name string `json:"name"`
	// Long name of a region
	Description string `json:"description"`
}

func (o *Region) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Region) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}
