// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ResponseAddSSHKey - The added or generated SSH public key. If a new key pair was generated, the response body contains a `private_key` property that *must* be saved locally. Lambda Cloud does not store private keys.
type ResponseAddSSHKey struct {
	// Information about a stored SSH key, which can be used to access instances over SSH
	Data SSHKey `json:"data"`
}

func (o *ResponseAddSSHKey) GetData() SSHKey {
	if o == nil {
		return SSHKey{}
	}
	return o.Data
}
