// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ResponseInstance - OK
type ResponseInstance struct {
	// Virtual machine (VM) in Lambda Cloud
	Data Instance `json:"data"`
}

func (o *ResponseInstance) GetData() Instance {
	if o == nil {
		return Instance{}
	}
	return o.Data
}
