// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type LaunchData struct {
	// The unique identifiers (IDs) of the launched instances. Note: if a quantity was specified, fewer than the requested quantity might have been launched.
	InstanceIds []string `json:"instance_ids"`
}

func (o *LaunchData) GetInstanceIds() []string {
	if o == nil {
		return []string{}
	}
	return o.InstanceIds
}

// ResponseLaunch - OK
type ResponseLaunch struct {
	Data LaunchData `json:"data"`
}

func (o *ResponseLaunch) GetData() LaunchData {
	if o == nil {
		return LaunchData{}
	}
	return o.Data
}
