// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Restart struct {
	// The unique identifiers (IDs) of the instances to restart
	InstanceIds []string `json:"instance_ids"`
}

func (o *Restart) GetInstanceIds() []string {
	if o == nil {
		return []string{}
	}
	return o.InstanceIds
}
