// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// SSHKey - Information about a stored SSH key, which can be used to access instances over SSH
type SSHKey struct {
	// Unique identifier (ID) of an SSH key
	ID string `json:"id"`
	// Name of the SSH key
	Name string `json:"name"`
	// Public key for the SSH key
	PublicKey string `json:"public_key"`
	// Private key for the SSH key. Only returned when generating a new key pair.
	PrivateKey *string `json:"private_key,omitempty"`
}

func (o *SSHKey) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *SSHKey) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *SSHKey) GetPublicKey() string {
	if o == nil {
		return ""
	}
	return o.PublicKey
}

func (o *SSHKey) GetPrivateKey() *string {
	if o == nil {
		return nil
	}
	return o.PrivateKey
}
