// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Terminate struct {
	// The unique identifiers (IDs) of the instances to terminate
	InstanceIds []string `json:"instance_ids"`
}

func (o *Terminate) GetInstanceIds() []string {
	if o == nil {
		return []string{}
	}
	return o.InstanceIds
}
