// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/squat/terraform-provider-lambda/internal/sdk/models/shared"
)

func (r *SSHKeyResourceModel) ToSharedAddSSHKey() *shared.AddSSHKey {
	var name string
	name = r.Name.ValueString()

	publicKey := new(string)
	if !r.PublicKey.IsUnknown() && !r.PublicKey.IsNull() {
		*publicKey = r.PublicKey.ValueString()
	} else {
		publicKey = nil
	}
	out := shared.AddSSHKey{
		Name:      name,
		PublicKey: publicKey,
	}
	return &out
}

func (r *SSHKeyResourceModel) RefreshFromSharedSSHKey(resp *shared.SSHKey) {
	r.ID = types.StringValue(resp.ID)
	r.Name = types.StringValue(resp.Name)
	r.PrivateKey = types.StringPointerValue(resp.PrivateKey)
	r.PublicKey = types.StringValue(resp.PublicKey)
}
