// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type Data struct {
	InstanceType                 InstanceType `tfsdk:"instance_type"`
	RegionsWithCapacityAvailable []Region     `tfsdk:"regions_with_capacity_available"`
}
