// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Specs struct {
	Gpus       types.Int64 `tfsdk:"gpus"`
	MemoryGib  types.Int64 `tfsdk:"memory_gib"`
	StorageGib types.Int64 `tfsdk:"storage_gib"`
	Vcpus      types.Int64 `tfsdk:"vcpus"`
}
